// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "kingscomp/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// Question is an autogenerated mock type for the Question type
type Question struct {
	mock.Mock
}

// AllIDs provides a mock function with given fields: ctx, prefix
func (_m *Question) AllIDs(ctx context.Context, prefix string) ([]string, error) {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for AllIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *Question) Get(ctx context.Context, id entity.ID) (entity.Question, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID) (entity.Question, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID) entity.Question); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Question)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveQuestions provides a mock function with given fields: ctx, index
func (_m *Question) GetActiveQuestions(ctx context.Context, index ...int64) ([]entity.Question, error) {
	_va := make([]interface{}, len(index))
	for _i := range index {
		_va[_i] = index[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuestions")
	}

	var r0 []entity.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...int64) ([]entity.Question, error)); ok {
		return rf(ctx, index...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...int64) []entity.Question); ok {
		r0 = rf(ctx, index...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...int64) error); ok {
		r1 = rf(ctx, index...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveQuestionsCount provides a mock function with given fields: ctx
func (_m *Question) GetActiveQuestionsCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveQuestionsCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MGet provides a mock function with given fields: ctx, ids
func (_m *Question) MGet(ctx context.Context, ids ...entity.ID) ([]entity.Question, error) {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []entity.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...entity.ID) ([]entity.Question, error)); ok {
		return rf(ctx, ids...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...entity.ID) []entity.Question); ok {
		r0 = rf(ctx, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...entity.ID) error); ok {
		r1 = rf(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MSet provides a mock function with given fields: ctx, ents
func (_m *Question) MSet(ctx context.Context, ents ...entity.Question) error {
	_va := make([]interface{}, len(ents))
	for _i := range ents {
		_va[_i] = ents[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...entity.Question) error); ok {
		r0 = rf(ctx, ents...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PushActiveQuestion provides a mock function with given fields: ctx, questions
func (_m *Question) PushActiveQuestion(ctx context.Context, questions ...entity.Question) error {
	_va := make([]interface{}, len(questions))
	for _i := range questions {
		_va[_i] = questions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PushActiveQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...entity.Question) error); ok {
		r0 = rf(ctx, questions...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, ent
func (_m *Question) Save(ctx context.Context, ent entity.Question) error {
	ret := _m.Called(ctx, ent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Question) error); ok {
		r0 = rf(ctx, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetField provides a mock function with given fields: ctx, id, fieldName, value
func (_m *Question) SetField(ctx context.Context, id entity.ID, fieldName string, value interface{}) error {
	ret := _m.Called(ctx, id, fieldName, value)

	if len(ret) == 0 {
		panic("no return value specified for SetField")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID, string, interface{}) error); ok {
		r0 = rf(ctx, id, fieldName, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestion creates a new instance of Question. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestion(t interface {
	mock.TestingT
	Cleanup(func())
}) *Question {
	mock := &Question{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
